### ISSUE TITLE
训练方式

### ISSUE THREAD

**Issue by wcnm231** [ziqiangcui/CaDiRec#3]
您好，我在跑实验的过程中发现，每10轮进行一次测试，这是公平的吗，因为后续的训练中是不是已经能看到过测试集中的项目，这样的话测试集精度高貌似是不公平的，这里让我感到非常困惑，期待您的回复，非常感谢

**Comment by ziqiangcui** [comment]
您好，测试集肯定不会参与训练的，训练集和测试集是在训练之前就划分好的没有任何交集。
每十轮测试一次只是方便观察，你也可以更改成300epoch或者400epoch训练完成再测试。

**Comment by wcnm231** [comment]
您好，我看了一下您的论文中，对比模型实验的结果，发现某些模型的结果与原文结果差距较大，比如DuoRec和MCLRec,您的对比结果远远低于原始论文中报告的结果，请问这是什么原因呢，是因为数据为了公平起见作了什么处理，还是说使用了什么显卡导致呢，期待您的回复，这对我来说很重要
