### ISSUE TITLE
对比实验结果

### ISSUE THREAD

**Issue by wcnm231** [ziqiangcui/CaDiRec#6]
您好，我看了一下您的论文中，对比模型实验的结果，发现某些模型的结果与原文结果差距较大，比如DuoRec和MCLRec,您的对比结果远远低于原始论文中报告的结果，请问这是什么原因呢，是因为数据为了公平起见作了什么处理，还是说使用了什么显卡导致呢，期待您的回复，这对我来说很重要

**Comment by ziqiangcui** [comment]
Regarding your question, the reasons have already been explained in the second paragraph of section 5.1.4 of our paper.
